Remove rbnacl-libsodium, will add rbnacl-devel RPM
ManageIQ/manageiq-appliance_console pull request #134
Opened 2020-11-10 14:49 UTC by jvlcek

see: https://github.com/RubyCrypto/rbnacl-libsodium#discontinued

@Fryguy, @agrare, @gtanzillo and @simaishi Need to add the rbnacl-devel RPM in a different PR

2020-11-10 15:06 UTC, Fryguy approved these changes
LGTM - will wait for the other PRs and merge them all together.

2020-11-10 15:07 UTC, Fryguy commented
Not sure how to release this...I'm thinking we should just a major version?  We don't want this accidentally pulled in to a system that doesn't have the rbnacl-devel package installed?

2020-11-10 18:14 UTC, Fryguy requested changes
@jvlcek If we remove this it will break the rpm build because we play some games with the on-disk assets post-bundle-install.  I think you will have to remove the following

https://github.com/ManageIQ/manageiq-rpm_build/blob/0f8f85208c656989608a8493d5aac0439ce12242/lib/manageiq/rpm_build/generate_gemset.rb#L82-L87

https://github.com/ManageIQ/manageiq-rpm_build/blob/0f8f85208c656989608a8493d5aac0439ce12242/lib/manageiq/rpm_build/generate_gemset.rb#L173-L176


cc @simaishi

2020-11-11 13:15 UTC, jvlcek commented
> @jvlcek If we remove this it will break the rpm build because we play some games with the on-disk assets post-bundle-install. I think you will have to remove the following
> 
> https://github.com/ManageIQ/manageiq-rpm_build/blob/0f8f85208c656989608a8493d5aac0439ce12242/lib/manageiq/rpm_build/generate_gemset.rb#L82-L87
> 
> https://github.com/ManageIQ/manageiq-rpm_build/blob/0f8f85208c656989608a8493d5aac0439ce12242/lib/manageiq/rpm_build/generate_gemset.rb#L173-L176
> 
> cc @simaishi

Please see: https://github.com/ManageIQ/manageiq-rpm_build/pull/117/commits/c653fd640865d4053ed6171bf2d71788a932c83d

2020-11-11 14:27 UTC, merged